[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"

# Add scheduled function
[[scheduled-functions]]
  function = "cron-fetch"
  schedule = "*/5 * * * *"